---
title: "script"
output: null
date: "2025-04-29"
---

```{r}
require(pacman)

p_load(
  tidyverse,
  tidymodels,
  ggplot2,
  plotly,
  leaflet,
  sf,
  visdat,
  geojsonsf,
  geojsonio,
  jsonlite,
  purrr,
  stringr,
  tm,
  stringi,
  skimr
  )
```
Carga de bases de datos
```{r}
raw_data_path <- '../data'

db_train <- read_csv(file.path(raw_data_path, 'train.csv'))

db_test <- read_csv(file.path(raw_data_path, 'test.csv'))

localidades <- read_delim(
  file.path(raw_data_path, 'poligonos_localidades.csv'), 
  delim = ';', 
  col_select = c(
    "Geo Shape 2", 
    "Nombre de la localidad"))

upl <- st_read(file.path(raw_data_path, "unidadplaneamientolocal.gpkg"))

policia <- read_delim(file.path(raw_data_path, 'centro-de-atencion-inmediata-2.csv'), 
  delim = ';', 
  col_select = c(
    "geopoint_"))

tm <- read_delim(file.path(raw_data_path, 'estaciones-de-transmilenio.csv'), 
  delim = ';', 
  col_select = c(
    'geopoint'))

sitp <- read_delim(file.path(raw_data_path, 'paraderos-sitp.csv'), 
  delim = ';', 
  col_select = c(
    'geopoint'))

ciclorutas <- read_delim(file.path(raw_data_path, 'ciclorutas.csv'), 
  delim = ';', 
  col_select = c(
    'Geo Shape'))

invasiones <- st_read(file.path(raw_data_path, 'ocupacion_ilegal.gpkg'))

m2_sf <- st_read(dsn = file.path(raw_data_path, 'valorintegralm2_greco'))
```
Localidades
```{r}
names(localidades) <- c(
    'geoshape',
    'localidad'
  )

localidades <- localidades %>% 
  filter(localidad != 'SUMAPAZ')

localidades_list <- map(localidades$geoshape, geojson_sf)
localidades_sf <- bind_rows(localidades_list)
localidades_sf$localidad <- localidades$localidad

# TRAIN
db_train <- st_as_sf(db_train, coords = c('lon', 'lat'), crs = 4326)
db_train <- st_join(db_train, localidades_sf["localidad"], left = TRUE)

# TEST
db_test <- st_as_sf(db_test, coords = c('lon', 'lat'), crs = 4326)
db_test <- st_join(db_test, localidades_sf["localidad"], left = TRUE)
```
UPLs
```{r}
upl <- upl %>% 
  select(
    'NOMBRE',
    'SHAPE'
  ) %>% 
  rename('upl' = 'NOMBRE')

# TRAIN
upl_sf <- st_transform(upl, crs = st_crs(db_train))

db_train <- st_join(db_train, upl_sf['upl'], left = TRUE)

# TEST
upl_sf <- st_transform(upl, crs = st_crs(db_test))

db_test <- st_join(db_test, upl_sf['upl'], left = TRUE)
```
Policía - CAIs
```{r}
policia <- policia %>% 
  filter(!is.na(geopoint_))

policia_sf <- policia %>%
  separate(geopoint_, into = c("lat", "lon"), sep = ", ", convert = TRUE) %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326)


policia_sf <- st_transform(policia_sf, 3857)

# TRAIN
db_train <- st_transform(db_train, 3857)
dist_matrix_policia <- st_distance(db_train, policia_sf)

db_train <- db_train %>%
  mutate(cai_mts = apply(dist_matrix_policia, 1, min)
  )

rm(dist_matrix_policia)

# TEST
db_test <- st_transform(db_test, 3857)
dist_matrix_policia <- st_distance(db_test, policia_sf)

db_test <- db_test %>%
  mutate(cai_mts = apply(dist_matrix_policia, 1, min)
  )

rm(dist_matrix_policia)
```
Estaciones de Transmilenio
```{r}
tm_sf <- tm %>%
  separate(geopoint, into = c("lat", "lon"), sep = ", ", convert = TRUE) %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326)

tm_sf <- st_transform(tm_sf, 3857)

# TRAIN
dist_matrix_tm <- st_distance(db_train, tm_sf)

db_train <- db_train %>%
  mutate(tm_mts = apply(dist_matrix_tm, 1, min))

rm(dist_matrix_tm)

# TEST
dist_matrix_tm <- st_distance(db_test, tm_sf)

db_test <- db_test %>%
  mutate(tm_mts = apply(dist_matrix_tm, 1, min))

rm(dist_matrix_tm)
```
Paradas de SITP
```{r}
sitp_sf <- sitp %>%
  separate(geopoint, into = c("lat", "lon"), sep = ", ", convert = TRUE) %>%
  st_as_sf(coords = c("lon", "lat"), crs = 4326)

sitp_sf <- st_transform(sitp_sf, 3857)

# TRAIN
viviendas_buffer_train <- st_buffer(db_train, dist = 100)

paraderos_por_vivienda_train <- st_intersects(viviendas_buffer_train, sitp_sf)

db_train$sitp_100m <- lengths(paraderos_por_vivienda_train)

# TEST
viviendas_buffer_test <- st_buffer(db_test , dist = 100)

paraderos_por_vivienda_test <- st_intersects(viviendas_buffer_test, sitp_sf)

db_test$sitp_100m <- lengths(paraderos_por_vivienda_test)
```
Ciclorutas
```{r}
names(ciclorutas) <- c('geoshape')

ciclorutas <- ciclorutas %>% 
  filter(!is.na(geoshape))

ciclorutas_list <- map(ciclorutas$geoshape, geojson_sf)
ciclorutas_sf <- bind_rows(ciclorutas_list)

ciclorutas_sf <- st_transform(ciclorutas_sf, 3857)

# TRAIN
dist_matrix_ciclorutas <- st_distance(db_train, ciclorutas_sf)

db_train <- db_train %>%
  mutate(ciclorutas_mts = apply(dist_matrix_ciclorutas, 1, min))

rm(dist_matrix_ciclorutas)

# TEST
dist_matrix_ciclorutas <- st_distance(db_test, ciclorutas_sf)

db_test <- db_test %>%
  mutate(ciclorutas_mts = apply(dist_matrix_ciclorutas, 1, min))

rm(dist_matrix_ciclorutas)
```
Invasiones
```{r}
invasiones <- invasiones %>% 
  select('geom')

invasiones_sf <- st_transform(invasiones, 3857)

# TRAIN
invasiones_por_vivienda_train <- st_intersects(viviendas_buffer_train, invasiones_sf)

db_train$invasiones_100m <- lengths(invasiones_por_vivienda_train)

# TEST
invasiones_por_vivienda_test <- st_intersects(viviendas_buffer_test, invasiones_sf)

db_test$invasiones_100m <- lengths(invasiones_por_vivienda_test)
```
Mediana de precio por m2 por manzanas
```{r}
m2_sf <- m2_sf %>% 
  rename('median_m2' = 'VrInt_Resi')

m2_sf <- m2_sf %>% filter(median_m2 != 0)

m2_sf <- st_transform(m2_sf, 4326)
m2_sf <- st_make_valid(m2_sf)

upl_sf <- st_transform(upl_sf, crs = st_crs(m2_sf))

m2_sf <- st_join(m2_sf, upl_sf['upl'], left = TRUE)

# TRAIN
db_train <- st_transform(db_train, 4326)

db_train <- st_join(db_train, m2_sf['median_m2'], left = TRUE)
db_train <- db_train %>% 
    distinct(property_id, .keep_all = TRUE)

db_train_na <- db_train[is.na(db_train$median_m2), ]

resultados_temp_train <- data.frame(property_id = character(), median_m2 = numeric(), stringsAsFactors = FALSE)

for (u in upl$upl) {
  nas <- db_train_na %>% filter(upl == u)
  m2 <- m2_sf %>% filter(upl == u)
  
  if (nrow(m2) == 0 | nrow(nas) == 0) next
  
  dist_m2 <- st_distance(nas, m2)
  index_m2 <- apply(dist_m2, 1, which.min)
  
  nas_result <- data.frame(
    property_id = nas$property_id,
    median_m2 = m2$median_m2[index_m2]
  )
  
  resultados_temp_train <- bind_rows(resultados_temp_train, nas_result)    
}

db_train <- db_train %>%
  left_join(resultados_temp_train, by = "property_id") %>%
  mutate(
    median_m2 = coalesce(median_m2.y, median_m2.x)
  ) %>%
  select(-median_m2.x, -median_m2.y)

# TEST
db_test <- st_transform(db_test, 4326)

db_test <- st_join(db_test, m2_sf['median_m2'], left = TRUE)

db_test <- db_test %>% 
  distinct(property_id, .keep_all = TRUE)

db_test_na <- db_test[is.na(db_test$median_m2), ]

resultados_temp_test <- data.frame(property_id = character(), median_m2 = numeric(), stringsAsFactors = FALSE)

for (u in upl$upl) {
  nas <- db_test_na %>% filter(upl == u)
  m2 <- m2_sf %>% filter(upl == u)
  
  if (nrow(m2) == 0 | nrow(nas) == 0) next
  
  dist_m2 <- st_distance(nas, m2)
  index_m2 <- apply(dist_m2, 1, which.min)
  
  nas_result <- data.frame(
    property_id = nas$property_id,
    median_m2 = m2$median_m2[index_m2]
  )
  
  resultados_temp_test <- bind_rows(resultados_temp_test, nas_result)
}

resultados_temp_test <- resultados_temp_test %>% 
    distinct(property_id, .keep_all = TRUE)

db_test <- db_test %>%
  left_join(resultados_temp_test, by = "property_id") %>%
  mutate(
    median_m2 = coalesce(median_m2.y, median_m2.x)
  ) %>%
  select(-median_m2.x, -median_m2.y)
```


```{r}
#df_long <- db_train %>%
#  mutate(price = log(price),
#         median_m2 = log(median_m2)) %>% 
#  pivot_longer(cols = c(price, median_m2), names_to = "precios", values_to = "valores")
#
## Graficar las curvas de densidad
#ggplot(df_long, aes(x = valores, fill = precios)) +
#  geom_density(alpha = 0.5) +
#  labs(title = "Distribuciones de log mediana por manzana y log precios reales",
#       x = "log(precios)",
#       y = "Densidad",
#       fill = "precios") +
#  theme_minimal()
```
Importación de datos de vías e inclusión de características de la vía más cercana a cada vivienda
```{r}
#vias <- read_delim(file.path(raw_data_path, 'estado-vias.csv'), 
#  delim = ';', 
#  col_select = c(
#    'Estado de la vías',
#    'Clasificación',
#    'KM_CARRIL',
#    'Geo Shape'
#    ))
#
#names(vias) <- c(
#  'estado_via',
#  'tipo_via',
#  'ancho_via',
#  'geoshape'
#  )
#
#vias <- vias %>% 
#  filter(!is.na(geoshape))
#
#vias <- vias %>% mutate(via_id = row_number())
#
#vias_list <- map(vias$geoshape, geojson_sf)
#vias_sf <- compact(vias_list) %>% bind_rows()
#
#vias_sf <- st_transform(vias_sf, 3857)
#
#dist_matrix_vias <- st_distance(db_train, vias_sf)
#
#db_train <- db_train %>%
#  mutate(via_mts = apply(dist_matrix_vias, 1, min),
#         via_id = apply(dist_matrix_vias, 1, which.min))
#
#db_train <- db_train %>% 
#  left_join(vias %>% select(-geoshape), by=c(via_id)) %>% 
#  select(-via_id)
```


```{r}
#ggplot() +
#  #geom_sf(data = db_train, color = "red", size = 0.1) +
#  geom_sf(data = localidades_sf, fill = "lightgray", color = "black", alpha = 0.2) +
#  geom_sf(data = invasiones_sf, color = "blue", size = 0.1) +
#  #geom_sf(data = tm_sf, color = "orange", size = 0.1) +
#  #geom_sf(data = sitp_sf, color = "blue", size = 0.1)
#  theme_minimal()
```
```{r}
#skim(db_train$sitp_100m)
```
Generación de variables a partir de texto
TRAIN
```{r}
db_train <- db_train %>%
  mutate(description_clean = stri_trans_general(description, "Latin-ASCII"))

corpus <- Corpus(VectorSource(db_train$description_clean))

corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, removeWords, stopwords('spanish'))
corpus <- tm_map(corpus, stripWhitespace)

#creación de matriz con palabras
dtm <-  TermDocumentMatrix(corpus)
tdm <- as.matrix(dtm)
freq_total <- rowSums(tdm)
df_freq_total <- as.data.frame(freq_total)
df_freq_total$word <- rownames(df_freq_total)
df_freq_total <- df_freq_total[order(-df_freq_total$freq_total),]

parqueadero <- c("parqueadero", "parqueaderos", "garajes", "garaje", "parqueo", "sotano")
parque <- c("parque", "parques")
avenidas <- c("vias", "carrera", "avenida", "principales", "autopista", 
              "transmilenio", "cra", "boyaca", "cll", "cali", "novena", 
              "avenidas", "esperanza", "americas", "via", "dorado", "septima",
              "ochenta", "nqs")
gimnasio <- c("gimnasio", "gym")

db_train <- db_train %>%
  mutate(
    parqueaderos = if_else(str_detect(description_clean, str_c(parqueadero, collapse = "|")), 1, 0),
    parque = if_else(str_detect(description_clean, str_c(parque, collapse = "|")), 1, 0),
    avenidas = if_else(str_detect(description_clean, str_c(avenidas, collapse = "|")), 1, 0),
    gimnasio = if_else(str_detect(description_clean, str_c(gimnasio, collapse = "|")), 1, 0),
    duplex = if_else(str_detect(description_clean, 'duplex'), 1, 0),
    piscina = if_else(str_detect(description_clean, "piscina"), 1, 0)
    )

rm(corpus)
rm(dtm)
rm(tdm)
rm(df_freq_total)
```
TEST
```{r}
db_test <- db_test %>%
  mutate(description_clean = stri_trans_general(description, "Latin-ASCII"))

corpus <- Corpus(VectorSource(db_test$description_clean))

corpus <- tm_map(corpus, content_transformer(tolower))
corpus <- tm_map(corpus, removePunctuation)
corpus <- tm_map(corpus, removeNumbers)
corpus <- tm_map(corpus, removeWords, stopwords('spanish'))
corpus <- tm_map(corpus, stripWhitespace)

#creación de matriz con palabras
dtm <-  TermDocumentMatrix(corpus)
tdm <- as.matrix(dtm)
freq_total <- rowSums(tdm)
df_freq_total <- as.data.frame(freq_total)
df_freq_total$word <- rownames(df_freq_total)
df_freq_total <- df_freq_total[order(-df_freq_total$freq_total),]

parqueadero <- c("parqueadero", "parqueaderos", "garajes", "garaje", "parqueo", "sotano")
parque <- c("parque", "parques")
avenidas <- c("vias", "carrera", "avenida", "principales", "autopista", 
              "transmilenio", "cra", "boyaca", "cll", "cali", "novena", 
              "avenidas", "esperanza", "americas", "via", "dorado", "septima",
              "ochenta", "nqs")
gimnasio <- c("gimnasio", "gym")

db_test <- db_test %>%
  mutate(
    parqueaderos = if_else(str_detect(description_clean, str_c(parqueadero, collapse = "|")), 1, 0),
    parque = if_else(str_detect(description_clean, str_c(parque, collapse = "|")), 1, 0),
    avenidas = if_else(str_detect(description_clean, str_c(avenidas, collapse = "|")), 1, 0),
    gimnasio = if_else(str_detect(description_clean, str_c(gimnasio, collapse = "|")), 1, 0),
    duplex = if_else(str_detect(description_clean, 'duplex'), 1, 0),
    piscina = if_else(str_detect(description_clean, "piscina"), 1, 0)
    )

rm(corpus)
rm(dtm)
rm(tdm)
rm(df_freq_total)
```


```{r}
write_rds(db_train, file.path(raw_data_path, 'train.rds'))
write_rds(db_test, file.path(raw_data_path, 'test.rds'))
```
